# 👾 Games/__init__.py Game Nodes for ComfyUI

from .Comfy_Chess import NODE_CLASS_MAPPINGS as CHESS_NODES
from .Comfy_Chess import NODE_DISPLAY_NAME_MAPPINGS as CHESS_DISPLAY

from .Card_random import NODE_CLASS_MAPPINGS as CARDRANDOM_NODES
from .Card_random import NODE_DISPLAY_NAME_MAPPINGS as CARDRANDOM_DISPLAY

from .Card_selector import NODE_CLASS_MAPPINGS as CARDOUT_NODES
from .Card_selector import NODE_DISPLAY_NAME_MAPPINGS as CARDOUT_DISPLAY

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(CHESS_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(CHESS_DISPLAY)

NODE_CLASS_MAPPINGS.update(CARDRANDOM_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(CARDRANDOM_DISPLAY)

NODE_CLASS_MAPPINGS.update(CARDOUT_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(CARDOUT_DISPLAY)

