# Chat/__init__.py

# 👾 OmiXDev/chat Chat Nodes for ComfyUI
# Includes Gemini and OpenAI Chat APIs

# Chat/__init__.py

from .chat_OpenAI import NODE_CLASS_MAPPINGS as OPENAI_NODES, NODE_DISPLAY_NAME_MAPPINGS as OPENAI_DISPLAY
from .chat_Gemini import NODE_CLASS_MAPPINGS as GEMINI_NODES, NODE_DISPLAY_NAME_MAPPINGS as GEMINI_DISPLAY
from .chat_Ollama import NODE_CLASS_MAPPINGS as OLLAMA_NODES, NODE_DISPLAY_NAME_MAPPINGS as OLLAMA_DISPLAY

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(OPENAI_NODES)
NODE_CLASS_MAPPINGS.update(GEMINI_NODES)
NODE_CLASS_MAPPINGS.update(OLLAMA_NODES)

NODE_DISPLAY_NAME_MAPPINGS.update(OPENAI_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(GEMINI_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(OLLAMA_DISPLAY)

