# Tools/__init__.py
# 👾 OmiXDev/Tools Nodes for ComfyUI

from .Resolution_Presets import NODE_CLASS_MAPPINGS as RES_PRESETS_NODES, NODE_DISPLAY_NAME_MAPPINGS as RES_PRESETS_DISPLAY
from .Cbeep import NODE_CLASS_MAPPINGS as BEEP_NODES, NODE_DISPLAY_NAME_MAPPINGS as BEEP_DISPLAY
from .Color_Picker import NODE_CLASS_MAPPINGS as COLOR_PICKER_NODES, NODE_DISPLAY_NAME_MAPPINGS as COLOR_PICKER_DISPLAY
from .Color_Presets import NODE_CLASS_MAPPINGS as COLOR_PRESETS_NODES, NODE_DISPLAY_NAME_MAPPINGS as COLOR_PRESETS_DISPLAY


NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(RES_PRESETS_NODES)
NODE_CLASS_MAPPINGS.update(BEEP_NODES)
NODE_CLASS_MAPPINGS.update(COLOR_PICKER_NODES)
NODE_CLASS_MAPPINGS.update(COLOR_PRESETS_NODES)

NODE_DISPLAY_NAME_MAPPINGS.update(RES_PRESETS_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(BEEP_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(COLOR_PICKER_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(COLOR_PRESETS_DISPLAY)